# Generated by Django 3.2.5 on 2022-08-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=255)),
                ('active_duration', models.CharField(max_length=255)),
                ('total_active_duration', models.CharField(max_length=255)),
                ('last_maintenance_date', models.CharField(max_length=255)),
                ('storage_capacity', models.CharField(max_length=255)),
                ('total_recordings', models.CharField(max_length=255)),
                ('last_transfer_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('issuance_date', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.AddField(
            model_name='devicehealth',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicestatus'),
        ),
    ]
