# Generated by Django 3.2.5 on 2022-08-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20220804_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehealth',
            name='name',
        ),
    ]
