# Generated by Django 3.2.5 on 2022-08-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_devicehealth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehealth',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devices.devicestatus'),
        ),
    ]
